import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ClaudeCodeAdapter } from "../src/adapters/claude-code.js";
import type { Ctx } from "../src/core/context.js";
import { init } from "../src/core/init.js";
import { restore } from "../src/core/restore.js";
import { diff } from "../src/core/diff.js";
import { save } from "../src/core/save.js";
import { status } from "../src/core/status.js";
import { readState } from "../src/state.js";
import { exists, listFiles } from "../src/fsutil.js";

let tmp: string, root: string, shed: string, ctx: Ctx, logs: string[];

const w = (p: string, c = "") => fs.mkdir(path.dirname(p), { recursive: true }).then(() => fs.writeFile(p, c));
const r = (p: string) => fs.readFile(p, "utf8");

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), "lshed-it-"));
  root = path.join(tmp, "claude");
  shed = path.join(tmp, "shed");
  logs = [];
  ctx = { adapter: new ClaudeCodeAdapter(root), shed, log: (l) => logs.push(l) };
  // 가짜 ~/.claude
  await w(path.join(root, "skills/alpha/SKILL.md"), "alpha v1");
  await w(path.join(root, "skills/alpha/ref/x.txt"), "x");
  await w(path.join(root, "skills/beta/SKILL.md"), "beta");
  await w(path.join(root, "agents/rev.md"), "reviewer");
  await w(path.join(root, "CLAUDE.md"), "# my rules\nbe nice\n");
  await w(path.join(root, "settings.json"), "{}"); // lshed 가 절대 건드리면 안 되는 파일
});
afterEach(() => fs.rm(tmp, { recursive: true, force: true }));

describe("init", () => {
  it("스캔한 부품을 창고에 복사하고 매니페스트·state 를 만든다", async () => {
    const { manifest, copied } = await init(ctx);
    expect(copied).toBe(4);
    expect(manifest.profiles.default).toEqual({ skills: ["alpha", "beta"], agents: ["rev"], instructions: ["main"] });
    expect(await r(path.join(shed, "skills/alpha/ref/x.txt"))).toBe("x");
    expect(await r(path.join(shed, "instructions/main.md"))).toContain("be nice");
    expect(await exists(path.join(shed, "lshed.yaml"))).toBe(true);
    const st = await readState(ctx.adapter);
    expect(st?.profile).toBe("default");
    expect(st?.managed.sort()).toEqual(["agents/rev.md", "lshed/instructions/main.md", "skills/alpha", "skills/beta"]);
    expect(await status(ctx)).toMatchObject({ drifted: [] });
    // 로컬은 그대로
    expect(await r(path.join(root, "CLAUDE.md"))).toBe("# my rules\nbe nice\n");
  });
  it("이미 초기화된 창고는 거부", async () => {
    await init(ctx);
    await expect(init(ctx)).rejects.toThrow(/이미 초기화/);
  });
});

describe("restore", () => {
  beforeEach(async () => {
    await init(ctx);
    // 두 번째 프로필: alpha 만, 지침 없음
    const y = await r(path.join(shed, "lshed.yaml"));
    await fs.writeFile(path.join(shed, "lshed.yaml"), y + "  minimal:\n    skills: [alpha]\n");
  });

  it("default 재적용: CLAUDE.md 를 import 목록으로 바꾸고 원본을 백업", async () => {
    const res = await restore(ctx, "default");
    const claude = await r(path.join(root, "CLAUDE.md"));
    expect(claude).toMatch(/^<!-- generated by lshed; profile: default -->/);
    expect(claude).toContain("@lshed/instructions/main.md");
    expect(await r(path.join(root, "lshed/instructions/main.md"))).toContain("be nice");
    expect(res.backedUp).toEqual(["CLAUDE.md"]);
    expect(res.removed).toEqual([]);
    expect(await r(path.join(res.backupDir!, "CLAUDE.md"))).toContain("be nice");
    const st = await readState(ctx.adapter);
    expect(st?.managed).toContain("CLAUDE.md");
    expect(st?.managed).toContain("lshed/instructions/main.md");
  });

  it("프로필 전환: 관리 집합에만 있던 것을 제거하고 사용자 파일은 남긴다", async () => {
    await restore(ctx, "default");
    await w(path.join(root, "skills/user-made/SKILL.md"), "mine"); // 관리 밖
    const res = await restore(ctx, "minimal");
    expect(res.removed.sort()).toEqual(["CLAUDE.md", "agents/rev.md", "lshed/instructions/main.md", "skills/beta"]);
    expect(await exists(path.join(root, "skills/beta"))).toBe(false);
    expect(await exists(path.join(root, "agents/rev.md"))).toBe(false);
    expect(await exists(path.join(root, "CLAUDE.md"))).toBe(false);
    expect(await exists(path.join(root, "skills/alpha/SKILL.md"))).toBe(true);
    expect(await exists(path.join(root, "skills/user-made/SKILL.md"))).toBe(true);
    expect(await r(path.join(root, "settings.json"))).toBe("{}");
    // 제거된 것은 백업됨
    expect(await r(path.join(res.backupDir!, "skills/beta/SKILL.md"))).toBe("beta");
    // 다시 default 로 돌아오면 복구
    await restore(ctx, "default");
    expect(await r(path.join(root, "skills/beta/SKILL.md"))).toBe("beta");
    expect((await readState(ctx.adapter))?.profile).toBe("default");
  });

  it("--dry-run 은 아무것도 쓰지 않는다", async () => {
    const before = await listFiles(root);
    const res = await restore(ctx, "minimal", { dryRun: true });
    expect(res.removed).toContain("skills/beta");
    expect(await listFiles(root)).toEqual(before);
    expect((await readState(ctx.adapter))?.profile).toBe("default");
  });

  it("없는 프로필은 오류", async () => {
    await expect(restore(ctx, "nope")).rejects.toThrow(/프로필 "nope" 이 없습니다/);
  });

  it("인자 없으면 마지막 프로필", async () => {
    await restore(ctx, "minimal");
    const res = await restore(ctx, undefined);
    expect(res.profile).toBe("minimal");
  });
});

describe("diff / save / status", () => {
  beforeEach(async () => { await init(ctx); await restore(ctx, "default"); });

  it("로컬 편집을 파일 단위로 보고하고 save 로 창고에 반영", async () => {
    await w(path.join(root, "skills/alpha/SKILL.md"), "alpha v2");
    await w(path.join(root, "skills/alpha/new.md"), "n");
    await fs.rm(path.join(root, "skills/alpha/ref/x.txt"));
    await w(path.join(root, "lshed/instructions/main.md"), "edited rules");
    const d = await diff(ctx);
    expect(d.map((x) => `${x.item.category}/${x.item.id}`)).toEqual(["skills/alpha", "instructions/main"]);
    expect(d[0].changes).toEqual([
      { status: "M", file: "SKILL.md" }, { status: "A", file: "new.md" }, { status: "D", file: "ref/x.txt" },
    ]);
    const st = await status(ctx);
    expect(st.drifted).toEqual(["skills/alpha", "instructions/main"]);

    const saved = await save(ctx, ["alpha"]);
    expect(saved).toEqual(["skills/alpha"]);
    expect(await r(path.join(shed, "skills/alpha/SKILL.md"))).toBe("alpha v2");
    expect(await exists(path.join(shed, "skills/alpha/ref/x.txt"))).toBe(false);
    expect((await diff(ctx)).map((x) => x.item.id)).toEqual(["main"]);
    await save(ctx);
    expect(await r(path.join(shed, "instructions/main.md"))).toBe("edited rules");
    expect(await diff(ctx)).toEqual([]);
  });

  it("모호한 id 는 거부", async () => {
    await w(path.join(root, "agents/alpha.md"), "a");
    const y = await r(path.join(shed, "lshed.yaml"));
    await fs.writeFile(path.join(shed, "lshed.yaml"), y.replace("- id: rev", "- id: rev\n    - id: alpha").replace("agents:\n      - rev", "agents:\n      - rev\n      - alpha"));
    await w(path.join(shed, "agents/alpha.md"), "a");
    await expect(save(ctx, ["alpha"])).rejects.toThrow(/모호/);
    expect(await save(ctx, ["agents/alpha"])).toEqual([]);
  });
});

describe("ignore / symlink (실환경에서 발견된 문제)", () => {
  it("node_modules 와 .git 은 창고에 담기지 않는다", async () => {
    await w(path.join(root, "skills/heavy/SKILL.md"), "h");
    await w(path.join(root, "skills/heavy/node_modules/dep/index.js"), "junk");
    await w(path.join(root, "skills/heavy/.git/config"), "junk");
    await w(path.join(root, "skills/heavy/src/a.ts"), "keep");
    await init(ctx);
    expect(await listFiles(path.join(shed, "skills/heavy"), [])).toEqual(["SKILL.md", "src/a.ts"]);
  });

  it("심볼릭 링크로 걸린 스킬도 잡고 내용으로 복사한다", async () => {
    const outside = path.join(tmp, "elsewhere/linked");
    await w(path.join(outside, "SKILL.md"), "linked content");
    await fs.symlink(outside, path.join(root, "skills/linked"));
    const { manifest } = await init(ctx);
    expect(manifest.components.skills.map((c) => c.id)).toContain("linked");
    const copied = path.join(shed, "skills/linked");
    expect((await fs.lstat(copied)).isSymbolicLink()).toBe(false);
    expect(await r(path.join(copied, "SKILL.md"))).toBe("linked content");
  });

  it("끊어진 링크는 건너뛴다", async () => {
    await fs.symlink(path.join(tmp, "gone"), path.join(root, "skills/broken"));
    const { manifest } = await init(ctx);
    expect(manifest.components.skills.map((c) => c.id)).not.toContain("broken");
  });

  it("--exclude 로 무거운 부품을 통째로 뺀다", async () => {
    const res = await init(ctx, { exclude: ["beta"] });
    expect(res.skipped).toEqual(["skills/beta"]);
    expect(res.manifest.components.skills.map((c) => c.id)).toEqual(["alpha"]);
    expect(await exists(path.join(shed, "skills/beta"))).toBe(false);
  });

  it("ignore 는 diff 에도 적용된다", async () => {
    await init(ctx);
    await restore(ctx, "default");
    await w(path.join(root, "skills/alpha/node_modules/x.js"), "junk");
    expect(await diff(ctx)).toEqual([]);
  });
});
