import { promises as fs } from "node:fs";
import YAML from "yaml";
import { type Ctx, manifestPath, loadManifest } from "./context.js";
import { readState, writeState } from "../state.js";
import { readLock, writeLock } from "../lock.js";
import { discover, notInManifest, inManifestNotInProfile, keyOf, type Found, type Discovered } from "./discover.js";
import { ingest, tidy } from "./ingest.js";
import { parseKey, type Manifest } from "../manifest.js";

export interface AddCandidates { fresh: Found[]; notInProfile: string[]; generated: Map<string, string> }

/** init 이후 이 환경에 새로 생긴 것. status 와 add 가 쓴다. */
export async function candidates(ctx: Ctx, m: Manifest, profile: string, d?: Discovered): Promise<AddCandidates> {
  d ??= await discover(ctx, m.exclude);
  return { fresh: notInManifest(m, d), notInProfile: inManifestNotInProfile(m, profile, d), generated: d.generated };
}

/**
 * 로컬에 새로 생긴 것을 창고에 넣는다 (init 의 증분판).
 * 키 없이 부르면 후보만 보여준다. 감지는 제안이고 확정은 사용자가 한다 (§3.7).
 * 넣은 부품은 현재 프로필과 관리 집합에 들어간다 — 이후 프로필 전환이 그것을 치울 수 있다는 뜻이다.
 */
export async function add(ctx: Ctx, keys: string[] = [], opts: { all?: boolean } = {}): Promise<string[]> {
  const state = await readState(ctx.adapter);
  if (!state) throw new Error("No profile applied. Run 'lshed init' or 'lshed restore <profile>' first.");
  const m = await loadManifest(ctx);
  const c = await candidates(ctx, m, state.profile);

  if (!keys.length && !opts.all) {
    if (!c.fresh.length) ctx.log("Nothing new outside the shed.");
    else {
      ctx.log(`${c.fresh.length} outside the shed (to add: lshed add <key...> or --all):`);
      for (const f of c.fresh) ctx.log(`  ${f.kind === "package" ? "≡" : " "} ${keyOf(f)}${f.kind === "package" ? `  ${f.pkg.source}` : f.kind === "entry" && f.warn ? `  ! ${f.warn}` : ""}`);
    }
    hint(ctx, c, state.profile);
    return [];
  }

  let chosen = c.fresh;
  if (keys.length) {
    chosen = keys.map((raw) => {
      // "agents/team/reviewer" 는 category=agents, id=team/reviewer. 카테고리 없이 "team/reviewer" 만 줘도 된다.
      const tryBoth = (k: { category?: string; id: string }) => c.fresh.filter((f) => f.id === k.id && (k.category === undefined || f.category === k.category));
      const k1 = parseKey(raw);
      let hits = tryBoth(k1);
      if (!hits.length && k1.category !== undefined) hits = tryBoth({ id: raw }); // 카테고리처럼 보인 첫 구간이 사실 id 의 일부
      if (!hits.length) {
        const known = Object.values(m.components).some((cs) => cs.some((x) => x.id === k1.id || x.id === raw)) || m.packages.some((p) => p.id === k1.id);
        throw new Error(known ? `"${raw}" is already in the shed. To put it in a profile, edit profiles in lshed.yaml.` : `"${raw}" was not found locally. 'lshed add' lists the candidates.`);
      }
      if (hits.length > 1) throw new Error(`"${raw}" is ambiguous: ${hits.map(keyOf).join(", ")}`);
      return hits[0];
    });
  }
  if (!chosen.length) { ctx.log("Nothing new outside the shed."); hint(ctx, c, state.profile); return []; }

  const doc = YAML.parseDocument(await fs.readFile(manifestPath(ctx), "utf8"));
  const lock = await readLock(ctx.shed);
  const res = await ingest(ctx, doc, state.profile, chosen, lock);
  tidy(doc);
  await fs.writeFile(manifestPath(ctx), doc.toString({ lineWidth: 0 }));
  if (res.packages.length) await writeLock(ctx.shed, lock);
  const managed = [...new Set([...state.managed, ...res.managed])].sort();
  await writeState(ctx.adapter, { ...state, managed, appliedAt: new Date().toISOString() });

  const added = chosen.map(keyOf);
  ctx.log(`\n${added.length} added to the shed and to profile "${state.profile}". Commit the shed: ${ctx.shed}`);
  if (res.packages.some((id) => chosen.find((f) => f.id === id && f.kind === "package" && f.pkg.into))) ctx.log(`Fill in the install command (install:) for git packages in lshed.yaml yourself.`);
  hint(ctx, { ...c, fresh: c.fresh.filter((f) => !chosen.includes(f)) }, state.profile);
  return added;
}

function hint(ctx: Ctx, c: AddCandidates, profile: string): void {
  const byPkg = new Map<string, number>();
  for (const by of c.generated.values()) byPkg.set(by, (byPkg.get(by) ?? 0) + 1);
  for (const [by, n] of byPkg) ctx.log(`  · ${n} generated by package ${by} are left out`);
  if (c.notInProfile.length) ctx.log(`${c.notInProfile.length} in the shed but not in profile "${profile}": ${c.notInProfile.join(", ")}  → add them under profiles in lshed.yaml`);
}
