import path from "node:path";
import type { Ctx } from "./context.js";
import { FRAGMENTS_DIR } from "./context.js";

const MARKER = "<!-- generated by lshed";

export function instructionsFile(ctx: Ctx): string {
  return path.join(ctx.adapter.root, ctx.adapter.instructionsFileName());
}

export function isGenerated(text: string): boolean {
  return text.trimStart().startsWith(MARKER);
}

/**
 * 지침 파일 내용 생성 (§3.3).
 * import 전략: 조각 경로를 @-import 로 나열 (지침 파일 위치 기준 상대 경로).
 * concat 전략: 조각 내용을 순서대로 이어붙인다.
 */
export function renderInstructions(
  ctx: Ctx,
  profile: string,
  fragments: { id: string; content: string }[],
): string {
  const head = `${MARKER}; profile: ${profile} -->\n<!-- Do not edit this file. Edit the fragments in your shed and run 'lshed restore'. -->\n\n`;
  if (ctx.adapter.instructionsStrategy() === "import") {
    return head + fragments.map((f) => `@${FRAGMENTS_DIR}/${f.id}.md`).join("\n") + "\n";
  }
  return head + fragments.map((f) => `<!-- ${f.id} -->\n${f.content.trimEnd()}\n`).join("\n");
}
