// 빌드된 CLI 를 임시 디렉터리에서 끝까지 돌려 본다. 실제 ~/.claude 는 건드리지 않는다.
// 사용: npm run build && npm run smoke   (다른 OS 에서 동작 확인용)
import { spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

const cli = path.resolve("dist/cli.js");
const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "lshed-smoke-"));
const A = path.join(tmp, "A"), B = path.join(tmp, "B"), shed = path.join(tmp, "shed");
const w = async (p, c) => { await fs.mkdir(path.dirname(p), { recursive: true }); await fs.writeFile(p, c); };
const J = (o) => JSON.stringify(o, null, 2);
let failed = 0;

function run(root, args, env = {}) {
  const r = spawnSync(process.execPath, [cli, "--root", root, "--shed", shed, ...args], { encoding: "utf8", env: { ...process.env, ...env } });
  const out = (r.stdout + r.stderr).trim();
  console.log(`\n$ lshed ${args.join(" ")}   (root=${path.basename(root)})\n${out.replace(/^/gm, "  ")}`);
  return { code: r.status, out };
}
function check(name, ok) { console.log(`${ok ? "  ✔" : "  ✘"} ${name}`); if (!ok) failed++; }

// 기기 A: 스킬 2개, CLAUDE.md, MCP 1개(시크릿), settings(홈 경로 훅 + enabledPlugins)
await w(path.join(A, "skills/alpha/SKILL.md"), "alpha");
await w(path.join(A, "skills/beta/SKILL.md"), "beta");
await w(path.join(A, "agents/rev.md"), "reviewer");
await w(path.join(A, "CLAUDE.md"), "# rules\n");
await w(`${A}.json`, J({ machineID: "A", mcpServers: { exa: { type: "stdio", command: "npx", args: ["-y", "exa-mcp-server"], env: { EXA_API_KEY: "sk-secret" } } } }));
await w(path.join(A, "settings.json"), J({ model: "opus", hooks: { Stop: [{ hooks: [{ type: "command", command: path.join(os.homedir(), ".claude", "hooks", "x") }] }] }, enabledPlugins: { "x@y": true } }));

let r = run(A, ["init"]);
check("init exit 0", r.code === 0);
check("init: mcp 시크릿 마스킹", r.out.includes("mcp/exa  (시크릿 → ${EXA_API_KEY})"));
check("init: settings 훅 담김", r.out.includes("+ settings/hooks"));
check("shed 에 시크릿 값 없음", !(await fs.readFile(path.join(shed, "mcp/exa.json"), "utf8")).includes("sk-secret"));
check("shed 훅 경로가 ${HOME}", (await fs.readFile(path.join(shed, "settings/hooks.json"), "utf8")).includes("${HOME}"));
check("enabledPlugins 안 담김", !(await fs.readdir(path.join(shed, "settings"))).includes("enabledPlugins.json"));

r = run(A, ["status"]);
check("status: 드리프트 없음", r.out.includes("드리프트 없음"));

// 기기 B: 빈 루트 + 다른 사람의 settings/mcp
await w(`${B}.json`, J({ machineID: "B", mcpServers: { theirs: { type: "stdio", command: "x" } } }));
await w(path.join(B, "settings.json"), J({ enabledPlugins: { "z@y": true } }));
r = run(B, ["restore", "default", "--dry-run"]);
check("dry-run exit 0", r.code === 0);
r = run(B, ["restore", "default"], { EXA_API_KEY: "on-B" });
check("restore exit 0", r.code === 0);
const bj = JSON.parse(await fs.readFile(`${B}.json`, "utf8"));
check("B.json: machineID 보존, theirs 보존, exa 자리표시자", bj.machineID === "B" && bj.mcpServers.theirs && bj.mcpServers.exa.env.EXA_API_KEY === "${EXA_API_KEY}");
const bs = JSON.parse(await fs.readFile(path.join(B, "settings.json"), "utf8"));
check("settings.json: enabledPlugins 보존, 훅 경로 실제 홈으로", bs.enabledPlugins["z@y"] === true && bs.hooks.Stop[0].hooks[0].command.startsWith(os.homedir()));
check("CLAUDE.md 생성", (await fs.readFile(path.join(B, "CLAUDE.md"), "utf8")).includes("generated by lshed"));
check("스킬 복사", (await fs.readFile(path.join(B, "skills/alpha/SKILL.md"), "utf8")) === "alpha");

r = run(B, ["restore"]);
check("재적용은 전부 =", r.code === 0 && !/^\s+[+~] /m.test(r.out));

// B 에서 새 스킬 + 로컬 편집 → add / diff / save
await w(path.join(B, "skills/gamma/SKILL.md"), "gamma");
await w(path.join(B, "skills/alpha/SKILL.md"), "alpha edited");
r = run(B, ["status"]);
check("status: 드리프트 1 + 창고 밖 2 (gamma, B 에 원래 있던 theirs)", r.out.includes("드리프트 1개: skills/alpha") && r.out.includes("창고 밖  2개: skills/gamma, mcp/theirs"));
r = run(B, ["add", "gamma"]);
check("add exit 0", r.code === 0 && (await fs.readFile(path.join(shed, "skills/gamma/SKILL.md"), "utf8")) === "gamma");
r = run(B, ["diff"]);
check("diff: alpha M", r.out.includes("skills/alpha") && r.out.includes("M "));
r = run(B, ["save"]);
check("save: alpha 반영", (await fs.readFile(path.join(shed, "skills/alpha/SKILL.md"), "utf8")) === "alpha edited");

// 프로필 전환: minimal (alpha 만) → beta·mcp·settings 제거 + 백업, theirs 는 남음
await fs.appendFile(path.join(shed, "lshed.yaml"), "  minimal:\n    skills: [alpha]\n");
r = run(B, ["restore", "minimal"]);
check("전환 exit 0", r.code === 0);
const bj2 = JSON.parse(await fs.readFile(`${B}.json`, "utf8"));
check("전환: exa 제거, theirs 유지", !bj2.mcpServers.exa && bj2.mcpServers.theirs);
check("전환: beta 제거", await fs.access(path.join(B, "skills/beta")).then(() => false, () => true));
check("백업 생성", r.out.includes("백업"));

r = run(B, ["list"]);
check("list exit 0", r.code === 0);

// sync (원격 없음): 커밋만
spawnSync("git", ["init", "-q"], { cwd: shed });
spawnSync("git", ["config", "user.name", "smoke"], { cwd: shed });
spawnSync("git", ["config", "user.email", "smoke@example.com"], { cwd: shed });
spawnSync("git", ["-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "--allow-empty", "-m", "seed"], { cwd: shed });
r = run(B, ["sync"]);
check("sync exit 0 (origin 없음)", r.code === 0 && r.out.includes("origin 이 없어"));

await fs.rm(tmp, { recursive: true, force: true });
console.log(`\n${failed ? `✘ ${failed}개 실패` : "✔ 스모크 통과"}  (${process.platform} ${os.release()}, node ${process.version})`);
process.exit(failed ? 1 : 0);
