import { promises as fs } from "node:fs";
import path from "node:path";
import YAML from "yaml";
import { z } from "zod";

/** lshed.lock — 패키지가 실제로 어느 커밋인지 (§6.3). 창고에 들어가며 커밋한다. */
const EntrySchema = z
  .object({ source: z.string(), rev: z.string().optional(), commit: z.string().optional() })
  .transform((e) => ({ source: e.source, rev: e.rev ?? e.commit ?? "" }));
export const LockSchema = z.object({
  version: z.literal(1),
  packages: z.record(z.string(), EntrySchema).default({}),
});
export type Lock = z.infer<typeof LockSchema>;

export const LOCK_FILE = "lshed.lock";

export async function readLock(shed: string): Promise<Lock> {
  try {
    return LockSchema.parse(YAML.parse(await fs.readFile(path.join(shed, LOCK_FILE), "utf8")));
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return { version: 1, packages: {} };
    throw new Error(`${LOCK_FILE} 을 읽을 수 없습니다: ${(e as Error).message}`);
  }
}

export async function writeLock(shed: string, lock: Lock): Promise<void> {
  const sorted: Lock = { version: 1, packages: Object.fromEntries(Object.entries(lock.packages).sort()) };
  await fs.writeFile(path.join(shed, LOCK_FILE), "# generated by lshed — do not edit; 'lshed update' refreshes it\n" + YAML.stringify(sorted));
}
